title: Bloomington Orchards Network
description: Tagline here
google_analytics:
theme: jekyll-theme-minimal
nav_items:
  - name: "about"
    url: "/"
  - name: "plants"
    url: "/plants/"
  - name: "register"
    url: "/register/"
  - name: "sponsors"
    url: "/sponsors/"